In [1]:
import pandas as pd

def commonRows(df1: pd.DataFrame, df2: pd.DataFrame) -> pd.Index:
  return pd.Index.intersection(df1.index, df2.index)

In [4]:
import numpy as np

rng = np.random.default_rng()

mat1 = rng.random((10,10))
mat2 = rng.random((10,10))

In [9]:
import string

df1 = pd.DataFrame(data=mat1, index = [_ for _ in string.ascii_letters[0:10]])
df2 = pd.DataFrame(data=mat2, index = [_ for _ in string.ascii_letters[5:15]])

In [10]:
df1

,0,1,2,3,4,5,6,7,8,9
a,0.745258,0.587514,0.083326,0.709019,0.446872,0.004214,0.579628,0.032218,0.973541,0.074208
b,0.268813,0.177202,0.640549,0.903223,0.954101,0.061637,0.076461,0.168599,0.690304,0.657414
c,0.295152,0.914796,0.375913,0.204457,0.895514,0.547673,0.584424,0.889754,0.314931,0.041580
d,0.952111,0.670097,0.005662,0.589628,0.273365,0.816899,0.031947,0.733255,0.769627,0.292339
e,0.861625,0.628956,0.259511,0.248506,0.802157,0.887251,0.755698,0.638007,0.768126,0.751173
f,0.926959,0.750671,0.487328,0.059729,0.578663,0.115305,0.934333,0.963463,0.690864,0.572810
g,0.684827,0.481870,0.883453,0.378485,0.882279,0.340747,0.421814,0.866455,0.860296,0.673927
h,0.263807,0.456723,0.299637,0.546826,0.365246,0.489916,0.235126,0.155290,0.772103,0.194287
i,0.416236,0.746890,0.958906,0.388717,0.364745,0.057433,0.615161,0.907374,0.144402,0.455444
j,0.409072,0.710162,0.636982,0.944754,0.169762,0.504316,0.631698,0.155854,0.841522,0.293137

In [11]:
commonRows(df1, df2)

Index(['f', 'g', 'h', 'i', 'j'], dtype='object')